### ISSUE TITLE
some suggestions on the workflow

### ISSUE THREAD

**Issue by wangleiphy** [DerFahrgast/jax-flow-matching#2]
- write out log to a file, so you can separate plotting and running scripts
- consider generating training data once and storing them in a file. 
- use pytest for testing 
- https://github.com/DerFahrgast/jax-flow-matching/blob/haiku/compare.py : this is not a good way to compare. Simply add a flag to your program, submit two jobs, and store results in a data file.

**Comment by wangleiphy** [comment]
see https://github.com/fermiflow/hydrogen for an example

**Comment by DreamSkanda** [comment]
- [x] Consider generating training data once and storing them in a file.
- [x] To compare, simply add a flag, submit two jobs, and store results in a data file.
- [x] Write out log to a file, so you can separate plotting and running scripts.
- [x] Use pytest for testing.

**Comment by DerFahrgast** [comment]
Closed by pr #12
